import os
import time
from typing import Any, Dict, List, Optional, Set, Tuple

import random

from fuzzer.fuzzer import Fuzzer
from runner.runner import Runner
from utils.coverage import Location
from utils.mutator import Mutator
from runner.function_coverage_runner import FunctionCoverageRunner
from schedule.power_schedule import MAX_SEEDS, PowerSchedule

from utils.object_utils import dump_object, get_md5_of_object
from utils.seed import Seed


class GreyBoxFuzzer(Fuzzer):

    def __init__(
            self,
            seeds: List[str],
            schedule: PowerSchedule,
            is_print: bool,
            output_dir: str = "_result",
            snapshot_interval: int = 1000,
            max_population: int = MAX_SEEDS) -> None:
        """Constructor.
        `seeds` - a list of (input) strings to mutate.
        `mutator` - the mutator to apply.
        `schedule` - the power schedule to apply.
        """
        super().__init__()
        self.is_print = is_print
        self.last_crash_time = self.start_time
        self.population = []
        self.file_map = {}
        self.covered_line: Set[Location] = set()
        self.seed_index = 0
        self.crash_map = dict()
        self.crash_ids: Set[Any] = set()
        self.seeds = seeds
        self.mutator = Mutator()
        self.schedule = schedule
        self.output_dir = output_dir
        self.snapshot_interval = snapshot_interval
        self.max_population = max_population
        self.persisted_seed_ids: Set[str] = set()
        self.persisted_crash_ids: Set[str] = set()
        self.last_snapshot_execs = 0
        self.last_new_seed: Optional[Seed] = None
        if is_print:
            print("""
┌───────────────────────┬───────────────────────┬───────────────────┬────────────────┬───────────────────┐
│        Run Time       │    Last Uniq Crash    │    Total Execs    │  Uniq Crashes  │   Covered Lines   │
├───────────────────────┼───────────────────────┼───────────────────┼────────────────┼───────────────────┤""")

    def result_path(self, *parts: str) -> str:
        return os.path.join(self.output_dir, *parts)

    def create_candidate(self) -> str:
        """Returns an input generated by fuzzing a seed in the population"""
        seed = self.schedule.choose(self.population)

        # Stacking: Apply multiple mutations to generate the candidate
        candidate = seed.data
        trials = min(len(candidate), 1 << random.randint(1, 5))
        for i in range(trials):
            candidate = self.mutator.mutate(candidate)
        return candidate

    def fuzz(self) -> str:
        """Returns first each seed once and then generates new inputs"""
        if self.seed_index < len(self.seeds):
            # Still seeding
            self.inp = self.seeds[self.seed_index]
            self.seed_index += 1
        else:
            # Mutating
            self.inp = self.create_candidate()

        return self.inp

    def print_stats(self):
        if not self.is_print:
            return

        def format_seconds(seconds):
            hours = int(seconds) // 3600
            minutes = int(seconds % 3600) // 60
            remaining_seconds = int(seconds) % 60
            return f"{hours:02d}:{minutes:02d}:{remaining_seconds:02d}"

        template = """│{runtime}│{crash_time}│{total_exec}│{uniq_crash}│{covered_line}│
├───────────────────────┼───────────────────────┼───────────────────┼────────────────┼───────────────────┤"""

        template = template.format(runtime=format_seconds(time.time() - self.start_time).center(23),
                                   crash_time=format_seconds(self.last_crash_time - self.start_time).center(23),
                                   total_exec=str(self.total_execs).center(19),
                                   uniq_crash=str(len(set(self.crash_map.values()))).center(16),
                                   covered_line=str(len(self.covered_line)).center(19))
        print(template)

    def persist_seed(self, seed: Seed, reason: str) -> str:
        """Persist one interesting seed, overwriting by input hash for de-duplication."""
        seed_id = get_md5_of_object(seed.data)
        path = self.result_path("seeds", f"{seed_id}.pkl")
        seed.saved_path = path
        seed.saved_reason = reason
        seed.saved_at = time.time()
        dump_object(path, seed)
        self.persisted_seed_ids.add(seed_id)
        return path

    def persist_crash(self, crash_id: Any, coverage: Set[Location]) -> Optional[str]:
        crash_key = get_md5_of_object(crash_id)
        if crash_key in self.persisted_crash_ids:
            return None

        record: Dict[str, Any] = {
            "input": self.inp,
            "crash_id": crash_id,
            "coverage": coverage,
            "total_execs": self.total_execs,
            "created_at": time.time(),
        }
        path = self.result_path("crashes", f"{crash_key}.pkl")
        dump_object(path, record)
        self.persisted_crash_ids.add(crash_key)
        return path

    def snapshot_extra(self) -> Dict[str, Any]:
        return {}

    def persist_snapshot(self, reason: str = "periodic") -> str:
        record: Dict[str, Any] = {
            "reason": reason,
            "timestamp": time.time(),
            "start_time": self.start_time,
            "total_execs": self.total_execs,
            "covered_line": self.covered_line,
            "unique_crashes": set(self.crash_map.values()),
            "population_size": len(self.population),
            "persisted_seed_count": len(self.persisted_seed_ids),
            "persisted_crash_count": len(self.persisted_crash_ids),
        }
        record.update(self.snapshot_extra())
        path = self.result_path("snapshots", f"{reason}-{self.total_execs:08d}.pkl")
        dump_object(path, record)
        self.last_snapshot_execs = self.total_execs
        return path

    def maybe_persist_snapshot(self) -> None:
        if self.snapshot_interval <= 0:
            return
        if self.total_execs - self.last_snapshot_execs >= self.snapshot_interval:
            self.persist_snapshot()

    def trim_population(self) -> None:
        if len(self.population) <= self.max_population:
            return
        try:
            self.schedule.assign_energy(self.population)
            self.population.sort(key=lambda seed: (seed.energy, seed.created_at), reverse=True)
        except Exception:
            self.population.sort(key=lambda seed: seed.created_at, reverse=True)
        del self.population[self.max_population:]

    def run(self, runner: FunctionCoverageRunner) -> Tuple[Any, str]:  # type: ignore
        """Run function(inp) while tracking coverage.
           If we reach new coverage,
           add inp to population and its coverage to population_coverage
        """
        self.last_new_seed = None
        result, outcome = super().run(runner)
        if len(self.covered_line) != len(runner.all_coverage):
            self.covered_line |= runner.all_coverage
            if outcome == Runner.PASS:
                # We have new coverage
                seed = Seed(self.inp, runner.coverage())
                self.population.append(seed)
                self.last_new_seed = seed
                self.persist_seed(seed, "new_coverage")
        if outcome == Runner.FAIL:
            self.last_crash_time = time.time()
            if result not in self.crash_ids:
                self.crash_map[self.inp] = result
                self.crash_ids.add(result)
            self.persist_crash(result, runner.coverage())

        self.trim_population()
        self.maybe_persist_snapshot()

        return result, outcome
